#include "snrt.h"
#include <stdint.h>
#include <stdio.h>

/* --- Bit-Stream State --- */
// We pack bits into this 32-bit register and flush them as bytes
uint32_t bit_buffer = 0;
int bit_count = 0;

/* --- Core Bit-Packing Function --- */
inline void push_bits(uint32_t code, int length, uint8_t **stream_out) {
    // 1. Shift the buffer and pack the new bits at the bottom
    bit_buffer = (bit_buffer << length) | (code & ((1 << length) - 1));
    bit_count += length;

    // 2. Flush full bytes to memory
    while (bit_count >= 8) {
        bit_count -= 8;
        // Extract the top 8 bits
        uint8_t byte = (bit_buffer >> bit_count) & 0xFF;
        *(*stream_out)++ = byte;
        
        // 3. JPEG Mandatory Byte Stuffing
        if (byte == 0xFF) {
            *(*stream_out)++ = 0x00;
        }
    }
}

/* --- VLI (Variable Length Integer) Helpers --- */
inline int get_vli_size(int16_t val) {
    if (val == 0) return 0;
    // Fast absolute value without branching
    int32_t abs_v = (val < 0) ? -val : val;
    // __builtin_clz counts leading zeros. 32 - clz = bits needed.
    return 32 - __builtin_clz(abs_v);
}

inline uint32_t get_vli_bits(int16_t val) {
    // JPEG requires 1's complement for negative numbers
    return (val > 0) ? val : (val - 1);
}

/* --- Mock Huffman Table --- */
// Real JPEG tables are complex. For this test, we map a few specific 
// (Run, Size) pairs to mock prefix codes so we can test the pipeline.
void get_huffman_prefix(int run, int size, uint32_t *code, int *len) {
    if (run == 0 && size == 4) { *code = 0x0B; *len = 4; return; } // (0,4) -> 1011
    if (run == 1 && size == 2) { *code = 0x1B; *len = 5; return; } // (1,2) -> 11011
    if (run == 1 && size == 1) { *code = 0x0C; *len = 4; return; } // (1,1) -> 1100
    if (run == 0 && size == 2) { *code = 0x01; *len = 2; return; } // (0,2) -> 01
    if (run == 0 && size == 0) { *code = 0x0A; *len = 4; return; } // EOB   -> 1010
    
    // Fallback for unexpected data
    *code = 0x00; *len = 0; 
}

/* --- The Huffman Kernel --- */
void process_huffman(int16_t *rle_in, uint8_t *jpg_stream) {
    uint8_t *stream_ptr = jpg_stream;
    
    // Reset global state
    bit_buffer = 0;
    bit_count = 0;

    for (int i = 0; i < 128; i += 2) {
        int16_t run = rle_in[i];
        int16_t val = rle_in[i+1];

        // Process End of Block (EOB)
        if (run == 0 && val == 0) {
            uint32_t prefix_code; int prefix_len;
            get_huffman_prefix(0, 0, &prefix_code, &prefix_len);
            push_bits(prefix_code, prefix_len, &stream_ptr);
            break; // Block is finished!
        }

        // 1. Calculate VLI Size and Bits
        int size = get_vli_size(val);
        uint32_t vli_bits = get_vli_bits(val);

        // 2. Get the Huffman Prefix Code for (Run, Size)
        uint32_t prefix_code;
        int prefix_len;
        get_huffman_prefix(run, size, &prefix_code, &prefix_len);

        // 3. Push Prefix, then push Value
        push_bits(prefix_code, prefix_len, &stream_ptr);
        push_bits(vli_bits, size, &stream_ptr);
    }

    // Flush any remaining bits left in the buffer by padding with 1s
    if (bit_count > 0) {
        push_bits((1 << (8 - bit_count)) - 1, 8 - bit_count, &stream_ptr);
    }
}

/* --- Main Entry Point --- */
int main() {
    uint32_t core_id = snrt_cluster_core_idx();
    uintptr_t base = (uintptr_t)snrt_l1_next();

    // Allocate memory in L1
    int16_t *rle_in = (int16_t *)((base + 63) & ~63);
    uint8_t *jpg_out = (uint8_t *)((uintptr_t)rle_in + 128 * sizeof(int16_t));

    // Compute Core Task
    if (snrt_is_compute_core() && core_id == 0) {
        
        // Load the exact pairs generated by our RLE step
        int16_t mock_pairs[] = {0, 15,  1, -2,  1, -1,  0, -2,  0, 0};
        for (int i = 0; i < 10; i++) rle_in[i] = mock_pairs[i];

        // Benchmark
        uint32_t start = snrt_mcycle();
        process_huffman(rle_in, jpg_out);
        uint32_t end = snrt_mcycle();

        // Print final Hex Byte Stream
        printf("\n--- FINAL JPEG BITSTREAM ---\n");
        printf("Raw Hex Bytes: ");
        
        // Print the first 6 bytes (should cover our small test block)
        for(int i=0; i<6; i++) {
            printf("%02X ", jpg_out[i]);
        }
        printf("\nCycles: %u\n", end - start);
    }

    snrt_cluster_hw_barrier();
    return 0;
}